src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\SoftDeleteable\Traits\SoftDeleteableEntity;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
#[Gedmo\SoftDeleteable(fieldName: 'deletedAt', timeAware: false, hardDelete: true)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    use SoftDeleteableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 25)]
    private $name;

    #[ORM\Column(type: 'string', length: 25)]
    private $first_name;

    #[ORM\Column(type: 'string', length: 25)]
    private $last_name;

    #[ORM\Column(type: 'string', length: 100, unique: true)]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'date')]
    private $birthday;

    #[ORM\ManyToOne(targetEntity: Group::class, inversedBy: 'users')]
    #[ORM\JoinColumn(nullable: false)]
    private $groups;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $avatar;

    #[ORM\OneToMany(targetEntity: Subject::class, mappedBy: "user")]
    private $subjects;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Score::class)]
    private $scores;

    #[ORM\Column(type: 'json', nullable: true)]
    private $address = [];

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    public const COLOR_GREEN = 'green';
    public const COLOR_YELLOW = 'yellow';
    public const COLOR_RED = 'red';

    public function __construct()
    {
        $this->scores = new ArrayCollection();
    }

    /**
     * @return mixed
     */
    public function getSubjects()
    {
        return $this->subjects;
    }

    /**
     * @param mixed $subjects
     */
    public function setSubjects($subjects): void
    {
        $this->subjects = $subjects;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getGroups(): ?Group
    {
        return $this->groups;
    }

    public function setGroups(?Group $groups): self
    {
        $this->groups = $groups;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getFullName()
    {
        return $this->getName() . " " . $this->getFirstName();
    }

    public function __toString(): string
    {
        return (string)$this->getFullName();
    }

    /**
     * @return Collection<int, Score>
     */
    public function getScores(): Collection
    {
        return $this->scores;
    }

    public function addScore(Score $score): self
    {
        if (!$this->scores->contains($score)) {
            $this->scores[] = $score;
            $score->setUser($this);
        }

        return $this;
    }

    public function removeScore(Score $score): self
    {
        if ($this->scores->removeElement($score)) {
            // set the owning side to null (unless already changed)
            if ($score->getUser() === $this) {
                $score->setUser(null);
            }
        }

        return $this;
    }

    public function getColor()
    {
        $scores = new ArrayCollection($this->getScores()->getValues());
        $min = 100;

        $scores->map(function ($value) use (&$min) {
            if ($value->getScore() != null &&$value->getScore() <= $min) {
                return $min = $value->getScore();
            }
        });

        return ($min == 5 ? User::COLOR_GREEN : ($min == 4 ? User::COLOR_YELLOW : User::COLOR_RED));
    }

    public function getAddress(): ?array
    {
        return $this->address;
    }

    public function setAddress(?array $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getFullAddress(): string
    {
        $city = $this->getAddress()['city'] ?? "null";
        $street = $this->getAddress()['street'] ?? "null";
        $home = $this->getAddress()['home'] ?? "null";

        return " Город " . $city ."\n" . " Улица " . $street . " Дом ". $home;
    }

    /**
     * @return string|null
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }
    /**
     * @return string[]
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @return mixed
     */
    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    /**
     * @return string
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }
}

src/Controller/ProfileController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Services\FileUploader;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\MakerBundle\FileManager;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Filesystem\Path;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

class ProfileController extends AbstractController
{
    #[Route('/profile', name: 'app_profile')]
    public function index()
    {
        $user = $this->getUser();
        $avatar = $user->getAvatar() ?? "";

        return $this->render('Profile/index.html.twig', ['user' => $user, 'avatar' => $avatar]);
    }

    #[Route('/profile/update_avatar', name: 'app_update_avatar')]
    public function updateAvatar(Request $request, FileUploader $fileUploader, EntityManagerInterface $entityManager)
    {
        $user = $this->getUser();

        $avatar = $request->files->get('avatar');
        if ($avatar) {
            $dir = $this->getParameter('avatar_path');
            $dirname = "$dir". "/" . $user->getId();
            $avatar_name = $fileUploader->upload($avatar, $dirname);
            $user->setAvatar('uploads/users/avatars/'.$user->getId() . "/" . $avatar_name);

            $entityManager->persist($user);
            $entityManager->flush();
        }

        return $this->redirect('/profile');
    }
}

templates/Profile/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <div class="container">
        <div class="card">
            <img src=" {{ absolute_url(avatar) }}" class="rounded mx-auto d-block" alt="Avatar">
            <form method="POST" enctype="multipart/form-data" action="{{ path('app_update_avatar') }}">
                <div class="form mb-3">
                    <input name="avatar" type="file" accept="image/*" class="form-control" id="avatar">
                </div>
                <button class="btn btn-primary" type="submit">Сохранить</button>
            </form>
            <div class="card-header">
                <div class="row">
                    <div class="col">
                        <div class="d-flex justify-content-end">
                            <h3> {{ user.name }} </h3>
                        </div>
                    </div>
                    <div class="col">
                        <div class="d-flex justify-content-end">
                            <a class="btn btn-outline-primary"
                               href="{{ path('app_user_edit', {'id': user.id}) }}">Edit</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <table class="table">
                    <tbody>
                    <tr>
                        <th>Id</th>
                        <td>{{ user.id }}</td>
                    </tr>
                    <tr>
                        <th>Name</th>
                        <td>{{ user.name }}</td>
                    </tr>
                    <tr>
                        <th>First_name</th>
                        <td>{{ user.firstName }}</td>
                    </tr>
                    <tr>
                        <th>Last_name</th>
                        <td>{{ user.lastName }}</td>
                    </tr>
                    <tr>
                        <th>Email</th>
                        <td>{{ user.email }}</td>
                    </tr>
                    <tr>
                        <th>Birthday</th>
                        <td>{{ user.birthday ? user.birthday|date('Y-m-d') : '' }}</td>
                    </tr>
                    <tr>
                        <th> Address</th>
                        <td>{{ user.getFullAddress() ?? null }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="d-flex justify-content-end">
            {{ include('user/_delete_form.html.twig') }}
        </div>
    </div>
{% endblock %}